### ISSUE TITLE
Plumber just returning [true] for the initial example

### ISSUE THREAD

**Issue by mingot** [trestletech/plumber#43] opened 2016-03-30 23:25 UTC
Hi,

I am testing the suggested base example on RStudio in a  a OSX Yosemite, but when accessing the API:
`$ curl "http://localhost:8000/mean"`

I keep getting the same response(via curl and browser):
`[true]`

Am I doing anything wrong?

**Comment by trestletech** [comment] 2016-04-14 03:39
Sorry for the late response. I'm not able to reproduce using the latest build from GitHub. What R file are you using?

**Comment by trestletech** [comment] 2016-04-26 02:53
Closing this for now since I'm not able to reproduce, but please reopen if you're still having trouble.

**Comment by mingot** [comment] 2016-04-26 07:33
I am just reproducing the sample myFile.R described in your github readme. 

Although I have downloaded the latest version of the package, every time I call
`r <- plumb("prova.R")`
seems to download the latest version from the repo as well. I have also simplified the function:
`normalMean <- function(samples=10){return(10)}`
But still getting the same response.

Thanks!

**Comment by trestletech** [comment] 2016-04-27 02:32
Hm.. I'm still unable to repro.

Can you explain what you mean about how running `plumb` "seems to download the latest version from the repo as well"? What is the output or what's leading you to believe that that's happening? I'm having a hard time explaining that one.

Can you send me the results of `sessionInfo()` and/or `devtools::session_info()` and also the `prova.R` file you're trying to use?

**Comment by trestletech** [comment] 2016-11-01 03:34
Closing due to lack of activity. If you're still able to reproduce this consistently please let me know.

**Closed by trestletech** 2016-11-01 03:34 UTC
Labels: bug
