### ISSUE TITLE
Set root path for a plumber API

### ISSUE THREAD

**Issue by nihonjinrxs** [trestletech/plumber#60] opened 2016-10-06 16:15 UTC
I'd love the ability to define a root path for the API, and have all plumbed endpoints be relative to that root path.

**Comment by ellisvalentiner** [comment] 2016-10-31 18:14
I think I know what you're referring to but could you provide an example?

**Comment by nihonjinrxs** [comment] 2016-10-31 22:48
For example, if I have an API defined in plumber with the following endpoints:
```
login
dosomething
dosomething/else
logout
```
normally, they'd be available at something like `http://example.com/<endpoint-name>`.

I'd like to be able to set a root path so that they can run at an arbitrary root path on that domain.  For example:

```
http://example.com/api/v1/<endpoint-name>
http://example.com/my-favorite-site/stuff-you-should-look-at/api/the-api-lives-here/<endpoint-name>
```

I'm thinking a simple parameter setting:
```
plumber$rootPath = "path/goes/here"
```
coupled with some simple prefixing in the router is what I'm looking for.

Is that doable?

**Comment by ellisvalentiner** [comment] 2016-10-31 23:09
Ok. That's pretty much the use case I thought you were referring to.

From my own testing (using decorators) you can use a variable path (e.g. `/api/<version>/`) where the variable is assigned in the global environment but only if it is a single resource.

I don't see a reason why this wouldn't work using the programmatic approach.

**Comment by trestletech** [comment] 2016-11-01 03:28
Good news/bad news.

Good news: you can accomplish this using an external router. I detail how to set this up with nginx using the `proxy_pass` directive here: http://plumber.trestletech.com/docs/docker-advanced/

Bad news: there isn't a way to do this built-in to plumber yet. But I'm tracking this issue here: https://github.com/trestletech/plumber/issues/36 The goal of that feature would be to support the notion of defining one plumber router for `/login` and one for `/dosomething` and then being able to "install" both of those routers at the `/api/v1` location.

That would allow you to modularize the plumber files that constitute a larger application.

I'm going to close this issue as a duplicate of that one, but if you think this issue has a unique component that I'm overlooking feel free to reopen and we can discuss.

**Closed by trestletech** 2016-11-01 03:28 UTC
