### ISSUE TITLE
formatting the body as JSON

### ISSUE THREAD

**Issue by Artem-fb** [trestletech/plumber#346] opened 2018-11-19 11:06 UTC
Hello!

I'm trying to reproduce code from the tutorial. https://www.rplumber.io/docs/routing-and-input.html#input-handling

--------------------

```r
#' @post /user
function(req, id, name){
  list(
    id = id,
    name = name,
    raw = req$postBody
  )
}
```
Running curl --data "id=123&name=Jennifer" "http://localhost:8000/user" will return:

```json
{
  "id": [123],
  "name": ["Jennifer"],
  "raw": ["id=123&name=Jennifer"]
}
```
Alternatively, `curl --data '{"id":123, "name": "Jennifer"}' "http://localhost:8000/user"` (formatting the body as JSON) will have the same effect.

-----------------------------

It works good, when I using `curl --data "id=123&name=Jennifer" "http://localhost:8000/user"`. 
And I have an error, when I try to use  `curl --data '{"id":123, "name": "Jennifer"}' "http://localhost:8000/user"`

```
{"error":["500 - Internal server error"],"message":["Error in (function (req, id, name) :
argument \"id\" is missing, with no default\n"]}
```

----------------------------

What I doing wrong?

**Comment by schloerke** [comment] 2018-12-06 20:59
@Artem-fb 

Glad to see you're using plumber!

I am unable to reproduce the error on my end.

Terminal 1, R process:
```r
cat(
"#' @post /user
function(req, id, name){
  list(
    id = id,
    name = name,
    raw = req$postBody
  )
}"
  , file = "input_handler.R"
)
install.packages("plumber")
# Installing package into ‘/Users/barret/z_R_library_3_5_1’
# (as ‘lib’ is unspecified)
# trying URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.5/plumber_0.4.6.tgz'
# Content type 'application/x-gzip' length 308762 bytes (301 KB)
# ==================================================
# downloaded 301 KB
# 
# 
# The downloaded binary packages are in
# 	/var/folders/0k/bxg5lhr92sq74mb1d446ql540000gp/T//RtmpwxrRFC/downloaded_packages
plumber::plumb("input_handler.R")$run(port = 8000)
# Starting server to listen on port 8000
# Running the swagger UI at http://127.0.0.1:8000/__swagger__/
```

Terminal 2
``` 
~: curl --data "id=123&name=Jennifer" "http://localhost:8000/user"
{"id":["123"],"name":["Jennifer"],"raw":["id=123&name=Jennifer"]}~: 
~: curl --data '{"id":123, "name": "Jennifer"}' "http://localhost:8000/user"
{"id":[123],"name":["Jennifer"],"raw":["{\"id\":123, \"name\": \"Jennifer\"}"]}~: 
~: 
```

-------------

Can you try again to see if it's still acting strange? If it is, could you provide me with a set of instructions to reproduce the error?

Thank you!

**Comment by AndrewYRoyal** [comment] 2019-08-20 19:13
I have experienced the same issue as above. Only the JSON format in the body does not work. I'm running on windows 10.

**Comment by schloerke** [comment] 2019-08-20 20:40
I believe this is the same error as in #436. 

Am going to close it until a reproducible script is provided.

**Closed by schloerke** 2019-08-20 20:40 UTC
Labels: need info, type: question
