### ISSUE TITLE
Plumber dplyr filter not working as expected

### ISSUE THREAD

**Issue by ignacio82** [trestletech/plumber#431] opened 2019-05-13 17:45 UTC
This is a [crosspost](https://stackoverflow.com/questions/56115769/plumber-dplyr-filter-not-working-as-expected?noredirect=1#comment98865704_56115769) because i'm not sure if the problem is that i'm making a mistake or a bug in plumber:

I wrote the following simple `plumber api`

```r
library(plumber)
library(dplyr)


#* @apiTitle TESTS API

#* Returns json with filtered mtcars
#* @param carb 
#* @param gear 
#* @get /test2
#* @serializer unboxedJSON
function(carb,gear) {
  mtcars %>% filter(gear == as.numeric(gear),
                    carb == as.numeric(carb)) %>% 
    jsonlite::toJSON()
  
}
```

Alas, when I call it the mtcars data is not filtered as I would expect:

```r
library(httr)
library(jsonlite)
library(dplyr)
response <- GET(url = 'http://127.0.0.1:3098/test2', 
                query = list(gear = 4,
                             carb = 4),
                encode="json")
content(response, encoding = "json") %>% fromJSON() %>% head()

   mpg cyl disp  hp drat    wt  qsec vs am gear carb
1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
6 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1


```

Am I doing something wrong?

**Comment by r2evans** [comment] 2019-05-13 20:34
I suspect [my answer on SO](https://stackoverflow.com/a/56119233/3358272) will cover this. I think the issue is not with `plumber`, but with the fact that `dplyr::filter` (and other similar functions) cannot intuit *which* `gear` you're referring to at each point in your expressions. You assume that the first `gear` refers to the frame column and the second refers to the function argument, but since `==` is commutative, there is no way to know or control where it "looks" first for a match. So it finds the first match it sees (likely the frame column), uses it on both sides, and does what is effectively an identity comparison (`gear == gear`).

A direct fix of your code:

```r
function(carb = NA, gear = NA) {
  c. <- carb
  g. <- gear
  mtcars %>%
    filter(is.na(g.) | gear == as.numeric(g.),
           is.na(c.) | carb == as.numeric(c.)) %>% 
    jsonlite::toJSON()
}
```

(Note that I recommend against `toJSON` here, as `curl ... | jq .` will not work correctly until `toJSON` is removed.)

**Comment by ignacio82** [comment] 2019-05-13 23:53
Thanks a lot @r2evans ! The reason why i added `jsonlite::toJSON()` is because I want to be able to convert the results to a data frame in R. For example: 

If my API looks like follows:

```r
library(plumber)
library(dplyr)


#* @apiTitle TESTS API

#* Returns json with filtered mtcars
#* @param carb 
#* @param gear 
#* @get /test2
#* @serializer unboxedJSON
function(carb = NA, gear = NA) {
  c. <- carb
  g. <- gear
  mtcars %>%
    filter(is.na(g.) | gear == as.numeric(g.),
           is.na(c.) | carb == as.numeric(c.))
}
```

Then when I call it from R:

```r
library(httr)
library(jsonlite)
library(dplyr)
response <- GET(url = 'http://127.0.0.1:9878/test2', 
                query = list(gear = 4,
                             carb = 4),
                encode="json")

my_df <- content(response, encoding = "json") %>% fromJSON() 

Error: Argument 'txt' must be a JSON string, URL or file.

```

While if I add `jsonlite::toJSON()` to the api I get this:

```r
> my_df
   mpg cyl  disp  hp drat    wt  qsec vs am
1 21.0   6 160.0 110 3.90 2.620 16.46  0  1
2 21.0   6 160.0 110 3.90 2.875 17.02  0  1
3 19.2   6 167.6 123 3.92 3.440 18.30  1  0
4 17.8   6 167.6 123 3.92 3.440 18.90  1  0
```

Is there a better way of doing getting back a data frame?

Thanks!

**Comment by r2evans** [comment] 2019-05-14 00:05
Using

```r
#* Returns json with filtered mtcars
#* @param carb 
#* @param gear 
#* @get /test2
#* @serializer unboxedJSON
func <- function(carb = NA, gear = NA) {
  c. <- carb
  g. <- gear
  mtcars %>%
    filter(is.na(g.) | gear == as.numeric(g.),
           is.na(c.) | carb == as.numeric(c.))
}
```

I can do:

```r
httr::GET("localhost:8000/test2") %>%
  httr::content(., encode='json') %>%
  do.call(rbind.data.frame, .) %>%
  head(.)
#      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
# 2   21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
# 210 21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
# 3   22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
# 4   21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
# 5   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
# 6   18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
```

Two benefits to doing it this way (not explicitly `toJSON`-ing it):

1. If you ever have need for something other than R to access your API, you don't have to double-decode things. It "just works".

2. When troubleshooting, you can use browsers to natively look at the return value. Without `toJSON`, I can see this, with the ability to collapse and browse the structured data:

    ![image](https://user-images.githubusercontent.com/5815808/57661756-01afe580-75a1-11e9-943a-26a2757c8e0c.png)

    but with `toJSON`, I can only see this:

    ![image](https://user-images.githubusercontent.com/5815808/57661781-1c825a00-75a1-11e9-8435-6f54660ca6d5.png)

    (This is Firefox, but other browsers have similar functionality, I believe.)

**Comment by ignacio82** [comment] 2019-05-14 13:14
Thanks a lot for the help. Feel free to close the issue, you have more than answer my question.
For future questions, is community.rstudio or StackOverflow a better place to ask questions? I[ asked a question ](https://community.rstudio.com/t/render-html-from-httr-post-inside-shiny-app/30586?u=ignacio)a couple of days ago on community.rstudio with no luck getting an answer.

**Comment by r2evans** [comment] 2019-05-14 14:47
I'm not the owner, I found your SO question interesting, googled, found this, and piped in again. Which is best? Idk, they can be hit-or-miss.On May 14, 2019 06:14, ignacio82 <notifications@github.com> wrote:Thanks a lot for the help. Feel free to close the issue, you have more than answer my question.
For future questions, is community.rstudio or StackOverflow a better place to ask questions? I asked a question a couple of days ago on community.rstudio with no luck getting an answer.

**Comment by schloerke** [comment] 2019-05-14 17:45
@r2evans Thank you for the help!

@ignacio82 Glad we could get it solved for you.  I would like to push for more community.rstudio.com involvement.  Momentum will pick up.  As with any crosspost, thank you for linking them.

**Closed by schloerke** 2019-05-14 17:45 UTC
