### ISSUE TITLE
Lines of documentation reverted in Swagger

### ISSUE THREAD

**Issue by dmenne** [trestletech/plumber#452] opened 2019-06-16 15:55 UTC
```
#* 1 First line
#* 2 Second line
#* 3 Second line
#* @get /getsinglebyid/<id>
function(res, id){
  q = make_join_sql_by_id(id)
  dbGetQuery(con, q)
}
```

Is documented in Swagger as:

`/getsinglebyid/{id} 3 Second line 2 Second line 1 First line`

**Comment by dmenne** [comment] 2019-06-16 15:57
```
R version 3.6.0 (2019-04-26) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 18362)  Matrix products: default  locale: [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 [4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       loaded via a namespace (and not attached):  [1] Rcpp_1.0.1           later_0.8.0          pillar_1.4.1         compiler_3.6.0        [5] prettyunits_1.0.2    remotes_2.0.4        tools_3.6.0          testthat_2.1.1        [9] digest_0.6.19        packrat_0.5.0        pkgbuild_1.0.3       pkgload_1.0.2        [13] bit_1.1-14           jsonlite_1.6         tibble_2.1.3         memoise_1.1.0        [17] RSQLite_2.1.1        debugme_1.1.0        pkgconfig_2.0.2      rlang_0.3.4          [21] cli_1.1.0            DBI_1.0.0            rstudioapi_0.10      curl_3.3             [25] RMariaDB_1.0.6       withr_2.1.2          hms_0.4.2            desc_1.2.0           [29] fs_1.3.1             devtools_2.0.2       rappdirs_0.3.1       rprojroot_1.3-2      [33] bit64_0.9-7          glue_1.3.1           crancache_0.0.0.9000 parsedate_1.2.0      [37] R6_2.4.0             processx_3.3.1       sessioninfo_1.1.1    plumber_0.4.7.9000   [41] rematch2_2.0.1       callr_3.2.0          blob_1.1.1           magrittr_1.5         [45] promises_1.0.1.9000  backports_1.1.4      ps_1.3.0             usethis_1.5.0        [49] assertthat_0.2.1     cranlike_1.0.2       httpuv_1.5.1.9000    stringi_1.4.3        [53] crayon_1.3.4
--
```

**Comment by jeffkeller87** [comment] 2019-06-17 13:10
Duplicate of #187

**Closed** 2019-06-17 13:14 UTC

**Comment by schloerke** [comment] 2019-06-17 13:44
Thank you @dmenne for the Issue and @jeffkeller87 for finding a duplicate. I have added a milestone to #187.
