### ISSUE TITLE
Error: Unknown specification for ssh_keys

### ISSUE THREAD

**Issue by nicksmithr** [trestletech/plumber#224] opened 2017-12-29 13:38 UTC
I'm trying to launch using Digital Ocean, following [Plumber's guide](https://www.rplumber.io/docs/hosting.html#digitalocean). I have set up a SSH, and added to `Settings` in my Digital Ocean account. I have also set up an environment variable as DO_PAT with a token for Digital Ocean's API.

Calling `droplets()` from within RStudio correctly lists the droplets. 
Calling `droplets_create()` instantiates, and creates droplets — `Using default ssh keys: Main`

However, calling `do_provision()`, (or `plumber::do_provision(dropletId)`) returns "`Error: Unknown specification for ssh_keys`".

This may be something I've misconfigured?

<details> <summary><strong>Session Info</strong></summary>

```> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] analogsea_0.6.0 plumber_0.4.2  

loaded via a namespace (and not attached):
 [1] zoo_1.8-0           reshape2_1.4.2      splines_3.4.1      
 [4] lattice_0.20-35     colorspace_1.3-2    stats4_3.4.1       
 [7] yaml_2.1.16         mgcv_1.8-17         base64enc_0.1-3    
[10] survival_2.41-3     rlang_0.1.1         ModelMetrics_1.1.0 
[13] nloptr_1.0.4        aws.s3_0.3.3        multcomp_1.4-6     
[16] foreach_1.4.3       plyr_1.8.4          stringr_1.2.0      
[19] lsmeans_2.26-3      MatrixModels_0.4-1  munsell_0.4.3      
[22] gtable_0.2.0        mvtnorm_1.0-6       codetools_0.2-15   
[25] coda_0.19-1         SparseM_1.77        httpuv_1.3.5       
[28] caret_6.0-76        curl_3.1            quantreg_5.33      
[31] pbkrtest_0.4-7      parallel_3.4.1      TH.data_1.0-8      
[34] Rcpp_0.12.14        xtable_1.8-2        openssl_0.9.9      
[37] scales_0.4.1        jsonlite_1.5        lme4_1.1-13        
[40] ggplot2_2.2.1       digest_0.6.13       stringi_1.1.5      
[43] grid_3.4.1          tools_3.4.1         sandwich_2.3-4     
[46] magrittr_1.5        lazyeval_0.2.0      tibble_1.3.3       
[49] crayon_1.3.4        aws.signature_0.3.5 car_2.1-5          
[52] MASS_7.3-47         Matrix_1.2-10       xml2_1.1.1         
[55] estimability_1.2    minqa_1.2.4         httr_1.3.1         
[58] rstudioapi_0.7      iterators_1.0.8     R6_2.2.2           
[61] nnet_7.3-12         nlme_3.1-131        compiler_3.4.1 
```
</details>

**Comment by trestletech** [comment] 2017-12-29 15:04
Can you run `traceback()` to get more information on exactly what inside of `do_provision` is failing?

**Comment by trestletech** [comment] 2017-12-29 15:29
Oh, interesting.

It looks like analogsea uses `list()` as the default for [`droplet_create`](https://github.com/sckott/analogsea/blob/a2cc5c86e00e87106dd5066241fee9b650846e85/R/droplets_create.R#L38), but `NULL` as the default for [`dropletS_create`](https://github.com/sckott/analogsea/blob/4c89d1a16c9918863c27acf1887b3b94c9e6a2d0/R/keys.R#L104). The underlying SSH key function has special handling for NULL but not for empty lists. [See](https://github.com/sckott/analogsea/blob/4c89d1a16c9918863c27acf1887b3b94c9e6a2d0/R/keys.R#L104)

So it's likely an analogsea bug, but to confirm you can try running `do_provision(ssh_keys=NULL)` which will pass that argument through and hopefully workaround the issue. If that fixes it, we can open a ticket in analogsea.

**Comment by nicksmithr** [comment] 2017-12-29 15:38
Seems to have worked (to some extent, now getting port 22 error, but think that's due to DO) —

```
> plumber::do_provision(ssh_keys=NULL)
THIS ACTION COSTS YOU MONEY!
Provisioning a new server for which you will get a bill from DigitalOcean.
Using default ssh keys: Main
NB: This costs $0.00744 / hour until you droplet_delete() it
Waiting for create .............
Error: port 22 is not open; wait a bit (try 5 - 10 sec.) and try again
```

**Comment by trestletech** [comment] 2017-12-29 18:29
Opened https://github.com/sckott/analogsea/issues/145 to track  the analogsea issue.

Are you able to SSH into the droplet created via `do_provision` in your terminal? If so, that just indicates that the timeout's not long enough. If not, then there may be a firewall problem.

The "is the server ready?" logic is super unsophisticated right now. Plumber just waits a hardcoded number of seconds and then tries to connect.

**Comment by nicksmithr** [comment] 2017-12-29 18:53
Great, thanks so much @trestletech. 

SSH'ing in seems to work from terminal. The only issue I'm having know, which may be unrelated, is deploying the API. Using `do_deploy_api`, I am getting --
```

> droplet <- analogsea::droplet(XXX)
> plumber::do_deploy_api(droplet = droplet,
+           path="/",
+           localPath = "/Users/Nick/Path/",
+           port = 8000
+           )
Warning: Permanently added 'XX' (ECDSA) to the list of known hosts.
Created symlink from /etc/systemd/system/multi-user.target.wants/plumber-.service to /etc/systemd/system/plumber-.service.
● plumber-.service - Plumber API
   Loaded: loaded (/etc/systemd/system/plumber-.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-12-29 18:50:57 UTC; 5s ago
 Main PID: 1904 (code=exited, status=203/EXEC)

Dec 29 18:50:57 ShakenLiquidation systemd[1]: Started Plumber API.
Dec 29 18:50:57 ShakenLiquidation systemd[1]: plumber-.service: Main process exited, code=exited, status=203/EXEC
Dec 29 18:50:57 ShakenLiquidation systemd[1]: plumber-.service: Unit entered failed state.
Dec 29 18:50:57 ShakenLiquidation systemd[1]: plumber-.service: Failed with result 'exit-code'.
Error: ssh failed
ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/folders/qg/09d4dr5x1013kc09m803smjc0000gn/T//Rtmp7KRhB2/hosts root@XXX 'systemctl status plumber-'
```

Is this related, or something I've done incorrectly?

**Comment by trestletech** [comment] 2018-01-10 14:44
It looks like that's actually your API crashing. I'd bet that there's some issue with your API. (I'm now realizing that a `do_logs()` function would be really helpful to allow you to inspect what's going on with your API.

If you can provide a minimally reproducible example of the API you're trying to deploy that encounters this I may be able to offer pointers.

**Comment by aitken711** [comment] 2018-03-01 18:56
I was experiencing problems similar to @nicksmithr when using `do_deploy_api`. If my API was already deployed on DO and I wanted to redeploy the API to the same port after making some code changes, I would get the same `Error: ssh failed` message. I was able to fix this by ssh'ing into my DO droplet and killing the process running on the port using the following command:

`kill $(lsof -t -i:8000)`

Once the process was killed, I was then successfully able to use `do_deploy_api` again.

**Comment by trestletech** [comment] 2018-04-10 16:03
https://github.com/sckott/analogsea/issues/144 has since been closed so closing this for now. Please ping if there are any lingering issues here on current versions.

**Closed by trestletech** 2018-04-10 16:03 UTC

**Comment by yoshiokiyamusu** [comment] 2019-07-16 02:38
Can you upload a video-tutorial on how to deploy Rplumber from scratch PLEASE
